print("Здарвствуйте! Введите 2 целых числа, (кроме 0)")
a, b = int(input()), int(input())
print("Сумма - ", a + b)
print("Разность -", a - b)
print("Произведение - ", a * b)
print("Частное - ", a / b)
